{% set name = "pyapp" %}
{% set version = "4.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyapp-{{ version }}.tar.gz
  sha256: 0247b8f074bdbb9ac8719a8c1bda59ea4668085ac0d409b262c6699c30dee7aa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0
    - python >=3.10,<4.0
  run:
    - python >=3.10,<4.0
    - argcomplete >=3.2,<4.0
    - colorama
    - yarl
    - importlib-metadata
    - typing_extensions

test:
  source_files:
    - tests
  imports:
    - pyapp
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys -k "not TestAsyncListenerSet" tests
  requires:
    - pip
    - pytest >=7.1.2
    - pytest-asyncio >=0.19
    - nox

about:
  home: https://github.com/pyapp-org/pyapp
  doc_url: https://docs.pyapp.info/
  summary: A Python application framework
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
