{% set name = "pyapp" %}
{% set version = "4.15.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyapp-{{ version }}.tar.gz
  sha256: ef2a051c7c921b06f17ca5a3eb26e692ef47ee966ee961069e3b44faacbc1a86

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0
    - python >=3.8,<4.0
  run:
    - python >=3.8,<4.0
    - argcomplete >=3.2.0,<4.0.0
    - colorama
    - importlib_metadata
    - yarl
    - sphinx

test:
  source_files:
    - tests
  imports:
    - pyapp
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys -k "not TestAsyncListenerSet" tests
  requires:
    - pip
    - pytest >=7.1.2
    - pytest-asyncio >=0.19
    - nox

about:
  home: https://github.com/pyapp-org/pyapp
  doc_url: https://docs.pyapp.info/
  summary: A Python application framework
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
