{% set name = "pyapp" %}
{% set version = "4.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyapp-{{ version }}.tar.gz
  sha256: 69ed56c0b1b7b4e1b58b2a9a850a31d7783b9f6f59b5f9a8256279dc42b30653

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry >=1.0
    - python >=3.8,<4.0
    - rtd-poetry
  run:
    - python >=3.8,<4.0
    - argcomplete
    - colorama
    - yarl

test:
  source_files:
    - tests
  imports:
    - pyapp
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests  # [unix]
    - pytest -vvv --capture=tee-sys -k "not TestFileLoader and not test_find_root_folder__outside_package" tests  # [win]
  requires:
    - pip
    - pytest >=7.1.2
    - pytest-asyncio >=0.19
    - nox

about:
  home: https://github.com/pyapp-org/pyapp
  doc_url: https://docs.pyapp.info/
  summary: A Python application framework
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
