{% set name = "pyapp" %}
{% set version = "4.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyapp-{{ version }}.tar.gz
  sha256: 394bccb3ff5296023a93d313b59e5616ce39693f6ace5a47c32668617b2ff097

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry >=1.0
    - python >=3.8,<4.0
    - rtd-poetry
  run:
    - python >=3.8,<4.0
    - argcomplete
    - colorama
    - yarl

test:
  source_files:
    - tests
  imports:
    - pyapp
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys -k "not TestAsyncListenerSet" tests
  requires:
    - pip
    - pytest >=7.1.2
    - pytest-asyncio >=0.19
    - nox

about:
  home: https://github.com/pyapp-org/pyapp
  doc_url: https://docs.pyapp.info/
  summary: A Python application framework
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
